trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'
  
strategy:
  matrix:
    Python27:
      python.version: '2.7'


steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
    
  - script: python sum.py
    displayName: 'Run sum.py'
    
  - script: |
      python -c "print('This is Section 1 Azure Demonstration'); print('KL-CSE')"
    displayName: 'Inline Python Script'